### ISSUE TITLE
API главной страницы

### ISSUE THREAD

**Issue by TheDim0n** [Digital-Pushkin-Lab/Text-Adaptation-Markup-Backend#2]
Реализовать API для посадочной страницы, проверить работоспособность с макетом. 
 
1) Обсудить запросы к странице и выписать их в комментарии (формат описания запроса ниже) 
2) Реализовать запросы 
3) Unit-тесты 
 
Формат описания каждого запроса: 
 
0) Краткое описание (цель) запроса 
1) URL (например, /users/get/) 
2) Метод запроса (GET, POST и тд) 
3) json, который будет получать backend от front'a 
4) json, который будет отправлять backend в ответ

**Comment by kazzart** [comment]
Какой нибудь комментарий

**Comment by kazzart** [comment]
Получение случайного текста:
1) texts/main
2) GET
3) --
4) {'text': string, 'main_text_id': int}

Загрузка нового текста:
1) texts/main
2) Post
3) {'text': string}
4) {'status': ok/error, 'main_text_id': int}

Сохранение отредактированного текста:
1) texts/edit
2) Post
3) {'text': string, 'main_text_id': int}
4) {'status': ok/error, 'edit_text_id': int}

Обновление текста:
1) texts/main
2) Get
3) {'main_text_id': int}
4) {'text': string}

**Comment by TheDim0n** [comment]
### Получение информации о проекте:
1. /info
2. GET
3. --
4.
```
{
    "about": string,
    "purpose": string
}
```

### Получение случайного текста:
1. /random
2. GET
3. --
4. 
```
{
    "text": string,
    "text_id": int
}
```

### Сохранение изменений для случайного текста:
1. /save/exist
2. POST
3.
```
{
    "text_id": int, 
    "adapted_text": string, 
    "changes": [
        {
            "number": int, 
            "index": int, 
            "text": string
        }
   ]
}
```
4. --

### Сохранение изменений для предложенной пары текстов
1. /save/exist
2. POST
3. 
```
{
    "initial_text": string, 
    "adapted_text": string, 
    "changes": [
        {
            "number": int, 
            "index": int, 
            "text": string
        }
   ]
}
```
4) --

**Comment by TheDim0n** [comment]
- [ ] Получение информации о проекте
- [ ] Получение случайного текста
- [ ] Сохранение изменений для случайного текста
- [ ] Сохранение изменений для предложенной пары текстов
